@echo off
echo MyDictionary Development Startup...

echo 1. Cleanup onceki processler...
call cleanup.bat

echo 2. Clean build...
dotnet clean
dotnet build

echo 3. Migration check...
dotnet ef database update --project MyDictionary.ApiService

echo 4. Aspire baslatiliyor...
dotnet run --project MyDictionary.AppHost