@echo off
echo MyDictionary Development Startup...

echo 1. Clean build...
dotnet clean
dotnet build

echo 2. Database migration...
dotnet ef database update --project MyDictionary.ApiService

echo 3. Starting Aspire...
dotnet run --project MyDictionary.AppHost